# Tested with OBJID:10 XPos:38 YPos:33 HEX:00000100000000000000010100000000000000010000 [:26]  (dngn_flame_00.zmb) (Contains Key)
OBJECT_IDS = {
    0: 'Crash if set directly (Undefined instruction)',
    1: 'Crash if set directly (Undefined instruction)',
    2: 'Stone',
    3: 'Pot with green rupee? inside',
    4: 'Fence without collision?',
    5: 'Switch',
    6: 'Candle',
    7: 'Blue Door',
    8: 'Gray Monster Door',
    9: 'Key-Door',
    10: 'Wooden Chest ',
    11: 'Hidden wooden chest',
    12: 'Hidden wooden chest',
    13: 'Crash if set directly',
    14: 'Pot with heart inside',
    15: 'Crash if set directly (Undefined instruction)',
    16: 'Orb Switch',
    17: 'Static fire obstacle (Beginning of fire temple)',
    18: 'Crash if set directly',
    19: 'Crash if set directly',
    20: 'Infinite falling???',
    21: 'Crash if set directly (Undefined instruction)',
    22: 'Crash if set directly (Undefined instruction)',
    23: 'Red / Blue orb switch',
    24: 'Red block',
    25: 'Grappling hook pole',
    26: 'Staircase up',
    27: 'Electro door',
    28: 'Crash if set directly',
    29: 'Arrow repeater',
    30: 'Safety field from pot',
    31: 'Sign',
    32: 'Crash if set directly (Undefined instruction)',
    33: 'Boss "door"',
    34: 'Crash if set directly (Undefined instruction)',
    35: 'Stone sign',
    36: 'Bomb flower',
    37: 'Crash if set directly (Undefined instruction)',
    38: 'Hourglass / Triforce door (Crash on activation if set directly)',
    39: 'Crash if set directly',
    40: 'Crash if set directly (Undefined instruction)',
    41: 'Crash if set directly (Undefined instruction)',
    42: 'Crash if set directly (Undefined instruction)',
    43: 'Crash if set directly (Undefined instruction)',
    44: 'Pillar key door',
    45: 'Crash if set directly (Undefined instruction)',
    46: 'Stone entrance',
    47: 'Crash if set directly (Undefined instruction)',
    48: 'House door (used in mercay island left-most house)',
    49: 'Crash if set directly',
    50: 'Crash if set directly (Undefined instruction)',
    51: 'Crash if set directly (Undefined instruction)',
    52: 'Frame',
    53: 'Crash if set directly (Undefined instruction)',
    54: 'Torch clicking map',
    55: 'Crash if set directly (Undefined instruction)',
    56: 'Crash if set directly (Undefined instruction)',
    57: 'Crash if set directly (Undefined instruction)',
    58: 'Crash if set directly (Undefined instruction)',
    59: 'Torch',
    60: 'Entrance (idk where it\'s used normally)',
    61: 'Wall crack',
    62: 'Eye switch',
    63: 'Breakable Yellow Brick',
    64: 'Block with cracks',
    65: 'Crash if set directly (Undefined instruction)',
    66: 'Shovel hole (after digging)',
    67: 'Pillar',
    68: 'Slightly different block with cracks',
    69: 'Spikes',
    70: 'Stone fence (without collision)',
    71: 'Pull lever',
    72: 'Crash if set directly (Undefined instruction)',
    73: 'Square gem holder',
    74: 'Crash if set directly (Undefined instruction)',
    75: 'Crash if set directly (Undefined instruction)',
    76: 'Crash if set directly (Undefined instruction)',
    77: 'Crash if set directly (Undefined instruction)',
    78: 'Crash if set directly (Undefined instruction)',
    79: 'Crash if set directly (Undefined instruction)',
    80: 'Crash if set directly (Undefined instruction)',
    81: 'Crash if set directly (Undefined instruction)',
    82: 'Crash if set directly (Undefined instruction)',
    83: 'Crash if set directly',
    84: 'Crash if set directly (Undefined instruction)',
    85: 'Crash if set directly (Undefined instruction)',
    86: 'Crash if set directly (Undefined instruction)',
    87: 'Crash if set directly (Undefined instruction)',
    88: 'Wind blower',
    89: 'Wind hole',
    90: 'Big Chest',
    91: 'Hidden Big Chest',
    92: 'Hidden Big Chest',
    93: 'Wall crack with fancy wall',
    94: 'Crash if set directly (Undefined instruction)',
    95: 'Staircase entrance',
    96: 'Something inside the floor',
    97: 'Crash if set directly',
    98: 'Crash if set directly (Undefined instruction)',
    99: 'Crash if set directly (Undefined instruction)',
    100: 'Crash if set directly (Undefined instruction)',
}

# Highest used ObjectID: '157
ITEM_IDS = {
    0: 'Nothing! ("Nothing is here") (Testet with 0a000000211800004f000000000000000101000000000000ff010000)',
    1: 'Key',
    2: 'Green Rupee (1)',
    3: 'Sword',
    4: 'Shield',
    5: 'Key (Textbox: "NO MESSAGE" (No Key Received!))',
    6: 'Force Gem (No Textbox)',
    7: 'Bombs',
    8: 'Bow (No TB (TextBox))',
    9: 'Big Green Rupee (100)',
    10: 'Heart Container',
    11: 'Key (Textbox: "NO MESSAGE" (No Key Received!))',
    12: 'Boomerang',
    13: 'Shovel (No TB)',
    14: 'Bombchus (No TB)',
    15: 'Boss Key',
    16: 'Red Potion (Textbox: "NO MESSAGE")',
    17: 'Key (Textbox: "NO MESSAGE" (No Key Received!))',
    18: 'Key (Textbox: "NO MESSAGE" (No Key Received!))',
    19: 'Treasure Chart (No TB)',
    20: 'Treasure Chart (No TB)',
    21: 'Treasure Chart (No TB)',
    22: 'Treasure Chart (No TB)',
    23: 'Key (Textbox: "NO MESSAGE" (No Key Received!))',
    24: 'Blue Rupee (5)',
    25: 'Red Rupee (20)',
    26: 'Big Red Rupee (200)',
    27: 'Big Gold Rupee (300)',
    28: 'Force Gem (Textbox: "NO MESSAGE" , No Force Gem in hands afterwards)',
    29: 'Red Force Gem (Textbox: "NO MESSAGE" , No Force Gem in hands afterwards)',
    30: 'Blue Force Gem (Textbox: "NO MESSAGE" , No Force Gem in hands afterwards)',
    31: 'Hammer (No TB)',
    32: 'Grappling Hook (No TB)',
    33: 'Square Crystal',
    34: 'Round Crystal',
    35: 'Triangle Crystal',
    36: 'Fishing Rod (No TB)',
    37: 'Cannon',
    38: 'Sun Key',
    39: 'Key (Textbox: "NO MESSAGE")',
    40: 'Quiver Upgrade',
    41: 'Bomb Bag Upgrade',
    42: 'Bombchu Bag Upgrade',
    43: 'Treasure (Textbox: "You got the ship part")',
    44: 'King\'s Key',
    45: 'Power Gem',
    46: 'Wisdom Gem',
    47: 'Courage Gem',
    48: 'Treasure (Pink Coral)',
    49: 'Treasure (White Pearl Loop)',
    50: 'Treasure (Dark Pearl Loop)',
    51: 'Treasure (Zora Scale)',
    52: 'Treasure (Goron Amber)',
    53: 'Treasure (Ruto Crown)',
    54: 'Treasure (Helmaroc Plume)',
    55: 'Treasure (Regal Ring)',
    56: 'Ghost Key',
    57: 'Freebie Card',
    58: 'Compliment Card',
    59: 'Complimentary Card',
    60: 'Regal Necklace (No TB)',
    61: 'Boat Crane',
    62: 'Hero\'s New Clothes',
    63: 'Telescope',
    64: 'guard notebook',
    65: 'Jolene\'s Letter',
    66: 'Prize Postcard',
    67: 'Wood Heart',
    68: 'Sword (No TB)',
    69: 'Key ("You got the Phantom Sword ...")',
    70: 'Key (No TB)',
    71: 'Key (No TB)',
    72: 'Key (No TB)',
    73: 'Key (No TB)',
    74: 'Key (No TB)',
    75: 'Treasure Map (SWQ) [South West Quadrant] #TODO Match ID with WIKI',
    76: 'Treasure Map (SWQ)',
    77: 'Treasure Map (SWQ)',
    78: 'Treasure Map (SWQ)',
    79: 'Treasure Map (SWQ)',
    80: 'Treasure Map (SWQ)',
    81: 'Treasure Map (SWQ)',
    82: 'Treasure Map (SWQ)',
    83: 'Treasure Map (NWQ) [North West Quadrant]',
    84: 'Treasure Map (NWQ)',
    85: 'Treasure Map (NWQ)',
    86: 'Treasure Map (NWQ)',
    87: 'Treasure Map (NWQ)',
    88: 'Treasure Map (NWQ)',
    89: 'Treasure Map (NWQ)',
    90: 'Treasure Map (NWQ)',
    91: 'Treasure Map (SEQ) [South East Quadrant]',
    92: 'Treasure Map (SEQ)',
    93: 'Treasure Map (SEQ)',
    94: 'Treasure Map (SEQ)',
    95: 'Treasure Map (SEQ)',
    96: 'Treasure Map (SEQ)',
    97: 'Treasure Map (SEQ)',
    98: 'Treasure Map (SEQ)',
    99: 'Treasure Map (NEQ) [North East Quadrant]',
    100: 'Treasure Map (NEQ)',
    101: 'Treasure Map (NEQ)',
    102: 'Treasure Map (NEQ)',
    103: 'Treasure Map (NEQ)',
    104: 'Treasure Map (NEQ)',
    105: 'Treasure Map (NEQ)',
    106: 'Treasure Map (NEQ)',
    107: 'Nothing ?',
    108: 'Nothing ?',
    109: 'Nothing ?',
    110: 'Nothing ?',
    111: 'Nothing ?',
    112: 'Nothing ?',
    113: 'Swordsman Scroll',
    114: 'Crimsonine',
    115: 'Azurine',
    116: 'Aquanine',
    117: 'Red Potion',
    118: 'Purple Potion',
    119: 'Yellow Potion',
    120: 'Sand of Hours (One Minute)',
    121: 'Golden Chimney #TODO Check if golden chimney everytime',
    122: 'Golden Handrail',
    123: 'Golden Cannon',
    124: 'Golden Hull',
    125: 'Ruto Crown',
    126: 'Ship Part (Random) #TODO check if same everytime',
    127: 'Stone Tablet / Slate',
    128: 'Bait (No TB)',
    129: 'Rupoor (10)',
    130: 'Rupoor (50)',
    131: 'Key ("You got some Sand of Hours (30 Seconds)")',
    132: 'Key ("You got some Sand of Hours (10 Seconds)")',
    133: 'Ship Part (Random)',
    134: 'Goron Amber',
    135: 'Ship Part (Random)',
    136: 'Key (No TB)',
    137: 'Key (No TB)',
    138: 'Key (No TB)',
    139: 'Key (No TB)',
    140: 'Key (No TB)',
    141: 'Key (No TB)',
    142: 'Key (No TB)',
    143: 'Key (No TB)',
    144: 'Key (No TB)',
    145: 'Key (No TB)',
    146: 'Key (No TB)',
    147: 'Key (No TB)',
    148: 'Key (No TB)',
    149: 'Key (No TB)',
    150: 'Key (No TB)',
    151: 'Key (No TB)',
    152: 'Key (No TB)',
    153: 'Key (No TB)',
    154: 'Key (No TB)',
    155: 'Key (No TB)',
    156: 'Key (No TB)',
    157: 'Key (No TB)',
    158: 'Key (No TB)',
    159: 'Key (No TB)',
    # TODO continue to 254
    255: 'Key (No TB)',
}
