name: test
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        pythonVersion: ["3.9", "3.10"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.pythonVersion }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.pythonVersion }}

      - name: Install tox
        run: |
          pip install --upgrade pip
          pip install tox

      - name: Run tests
        run: |
          tox
